services:
  - type: web
    name: fraud-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

  - type: web
    name: fraud-frontend
    env: python
    plan: free
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: FRAUD_API_URL
        value: https://fraud-detection-api-wb1m.onrender.com
